apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-bg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bg
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bg
    spec:
      containers:
        - name: bg-demo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
  strategy:
    blueGreen:
      activeService: {{ .Release.Name }}-active
      previewService: {{ .Release.Name }}-preview
      autoPromotionEnabled: false

