apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-active
spec:
  selector:
    app: {{ .Release.Name }}-bg
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}

---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
spec:
  selector:
    app: {{ .Release.Name }}-bg
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}