apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-first
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  order: "I deploy first"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-second
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  order: "I deploy second"